### ISSUE TITLE
kernel_require.rb:55:in `require': cannot load such file -- orogen (LoadError)

### ISSUE THREAD

**Issue by CK0916** [orocos-toolchain/orogen#124]
Hi,
i run "orocreate-pkg mycomponent", then make it. The terminal display like this：

`/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- orogen (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/wangzheng/orocos_toolchain/install/bin/typegen:2:in `<main>'
CMake Error at /home/wangzheng/orocos_toolchain/install/lib/cmake/orocos-rtt/UseOROCOS-RTT.cmake:611 (add_subdirectory):
  add_subdirectory given source "/home/wangzheng/Robot/build/typekit" which
  is not an existing directory.
Call Stack (most recent call first):
  CMakeLists.txt:34 (orocos_typegen_headers)
`
What‘s the problem? Is there something wrong with ruby on my computer. And the system is Ubuntu16.04.

**Comment by doudou** [comment]
I personally don't support orogen/typegen within the orocos-toolchain install. Ping @smits

**Comment by ymkim92** [comment]
I have the same problem. And I think this is the closer reason to the problem:
```
$ orogen
Traceback (most recent call last):
	2: from /opt/orocos/bin/orogen:4:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- orogen (LoadError)
```
